#!/usr/bin/env bash
set -xeuo pipefail

# remove kernel
mapfile -t OLD_KERNELS < <(rpm -qa | grep -E '^kernel(-core|-modules|-modules-core|-modules-extra)?-[0-9]' || true)
if [ "${#OLD_KERNELS[@]}" -gt 0 ]; then
  rpm --erase --allmatches --nodeps "${OLD_KERNELS[@]}"
fi
rm -rf /usr/lib/modules/*

# disable rpm-ostree/dracut hook
pushd /usr/lib/kernel/install.d
cp 05-rpmostree.install /tmp/05-rpmostree.install.bak
cp 50-dracut.install /tmp/50-dracut.install.bak
printf '%s\n' '#!/bin/sh' 'exit 0' > 05-rpmostree.install
printf '%s\n' '#!/bin/sh' 'exit 0' > 50-dracut.install
chmod +x 05-rpmostree.install 50-dracut.install
popd

# pull kernel
skopeo copy --retry-times 3 docker://ghcr.io/ublue-os/akmods:ogc-44 dir:/tmp/akmods
AKMODS_TGZ=$(jq -r '.layers[].digest' /tmp/akmods/manifest.json | cut -d: -f2)
tar -xzf "/tmp/akmods/${AKMODS_TGZ}" -C /tmp

# install ogc kernel
dnf -y install /tmp/kernel-rpms/*.rpm
rm -rf /tmp/akmods /tmp/kernel-rpms

# restore hooks
cp /tmp/05-rpmostree.install.bak /usr/lib/kernel/install.d/05-rpmostree.install
cp /tmp/50-dracut.install.bak /usr/lib/kernel/install.d/50-dracut.install
rm -f /tmp/05-rpmostree.install.bak /tmp/50-dracut.install.bak

rpm -qa | grep -E '^kernel.*-ogc'
[ "$(ls -1 /usr/lib/modules | wc -l)" -eq 1 ]
