#!/usr/bin/env bash
set -euo pipefail

curl -Lo /tmp/sysc-greet.rpm https://github.com/Nomadcxx/sysc-greet/releases/download/v1.1.9/sysc-greet-1.1.9-1.x86_64.rpm
dnf install -y /tmp/sysc-greet.rpm
rm -f /tmp/sysc-greet.rpm
