#!/usr/bin/env bash
set -euo pipefail

for zone in public FedoraWorkstation home; do
  # open kdeconnect ports (1714-1764/tcp+udp)
  firewall-offline-cmd --zone="$zone" --add-service=kdeconnect
  # open localsend ports (53317/tcp+udp)
  firewall-offline-cmd --zone="$zone" --add-port=53317/tcp
  firewall-offline-cmd --zone="$zone" --add-port=53317/udp
done
