---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: fedora-ublue-niri-testing
# description will be included in the image's metadata
description: Personal OS for nvidia-laptop.

base-image: ghcr.io/ublue-os/base-main
image-version: latest

modules:
#  - from-file: general/repos.yml
  - from-file: general/niri.yml
  - from-file: general/packages.yml
  - from-file: general/flatpak.yml
  - from-file: general/config.yml

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
