modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: script
    scripts:
      - setup-rime-build
      - install-megacmd
      - install-extest
      - setup-firewall # kdeconnect ports
      - install-fonts # fonts (maple-mono + lxgw-bright)
      - install-papirus # latest papirus from upstream (fedora package is outdated)
      - setup-plymouth-theme

  - type: script
    snippets:
      - "rm -rf /usr/share/doc/*"
      - "rm -rf /usr/src/*"
      - "mkdir -p /etc/skel/.config/niri && cp -r /usr/share/niri-config/* /etc/skel/.config/niri/" # 新用户自动带 niri 配置

  - type: systemd
    system:
      enabled:
        - ly.service
        - hide-grub.service

      disabled:
        - getty@tty2.service
    user:
      enabled:
        - mega-cmd-server
        - polkit-agent
        - udiskie

  - type: justfiles
    install: true
    include:
      - setup-automount.just
      - pick-icon.just
      - setup-niri.just
      - setup-opentabletdriver.just
      - setup-rime.just
      - setup-shell.just
      - setup-virtualization.just
