modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: script
    scripts:
      - setup-rime-build
      - install-megacmd
      - install-extest
      - install-fonts # fonts (maple-mono + lxgw-bright)
      - setup-plymouth-theme

  - type: script
    snippets:
      - "rm -rf /usr/share/doc/*"
      - "rm -rf /usr/src/*"

  - type: systemd
    system:
      enabled:
        - ly.service

      disabled:
        - getty@tty2.service
    user:
      enabled:
        - mega-cmd-server
        - udiskie

  - type: justfiles
    install: true
    include:
      - setup-automount.just
      - setup-niri.just
      - setup-opentabletdriver.just
      - setup-rime.just
      - setup-shell.just
