modules:
  - type: files
    files:
      - usr: /usr

  - type: script
    scripts:
      - setup-rime-build
      - install-megacmd
      - install-sysc-greet

  - type: systemd
    system:
      enabled:
        - greetd
    user:
      enabled:
        - mega-cmd-server
#        - kdeconnectd

  - type: justfiles
    install: true


